### PR TITLE
split json call into sub calls to void esp run out of memory

### PR DESCRIPTION
**Pull request by volkerrichert**
also remove remove "xxx" as default MAC for new devices

### CODE REVIEW

**Comment by volkerrichert** [comment]
I have to add the info request. some devices are shown offline even if they are online

**Comment by GermanBluefox** [comment]
@DutchmanNL Can anyone verify it?

**Comment by DutchmanNL** [comment]
> @DutchmanNL Can anyone verify it?

working on it, will update this weekend.

sorry forgot to set assignee :/

**Comment by DutchmanNL** [comment]
@volkerrichert thank you for this suggestion, change slightly different implemented in line with my coding style.
API /json is not called anymore, pallets and effects only if not available I memory. Info and states are pulled at every intervall

https://github.com/iobroker-community-adapters/ioBroker.wled/commit/7a5cd533629421afb77ccc4069594b6915c23d32

**Pull request closed without merging**
